// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQp1mr-uwPFyEiPVwqulqtEfMYfdBAF0',
    appId: '1:602768561452:web:070acac2657acca4460889',
    messagingSenderId: '602768561452',
    projectId: 'conocet-6836f',
    authDomain: 'conocet-6836f.firebaseapp.com',
    storageBucket: 'conocet-6836f.firebasestorage.app',
    measurementId: 'G-FFSL8XBBET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLDvbooMhVAL9V6g9bbT6fNyKD4zDUuM',
    appId: '1:602768561452:android:cf75cc208f74a562460889',
    messagingSenderId: '602768561452',
    projectId: 'conocet-6836f',
    storageBucket: 'conocet-6836f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCibBIYPv36MwUOc_PN5al-eKbmFdAnYc0',
    appId: '1:602768561452:ios:ef902f35455dafaa460889',
    messagingSenderId: '602768561452',
    projectId: 'conocet-6836f',
    storageBucket: 'conocet-6836f.firebasestorage.app',
    iosBundleId: 'com.example.testVocacional',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCibBIYPv36MwUOc_PN5al-eKbmFdAnYc0',
    appId: '1:602768561452:ios:ef902f35455dafaa460889',
    messagingSenderId: '602768561452',
    projectId: 'conocet-6836f',
    storageBucket: 'conocet-6836f.firebasestorage.app',
    iosBundleId: 'com.example.testVocacional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQp1mr-uwPFyEiPVwqulqtEfMYfdBAF0',
    appId: '1:602768561452:web:bb0363c28f7e328a460889',
    messagingSenderId: '602768561452',
    projectId: 'conocet-6836f',
    authDomain: 'conocet-6836f.firebaseapp.com',
    storageBucket: 'conocet-6836f.firebasestorage.app',
    measurementId: 'G-N9PV2WJQCQ',
  );
}
